In [1]:
import pandas as pd
pd.read_parquet("data/driver_stats.parquet")

,event_timestamp,driver_id,conv_rate,acc_rate,avg_daily_trips,created
0,2024-10-19 23:00:00+00:00,1005,0.729629,0.586597,838,2024-11-03 23:16:06.230
1,2024-10-20 00:00:00+00:00,1005,0.956828,0.239775,37,2024-11-03 23:16:06.230
2,2024-10-20 01:00:00+00:00,1005,0.094842,0.350396,799,2024-11-03 23:16:06.230
3,2024-10-20 02:00:00+00:00,1005,0.309115,0.635729,329,2024-11-03 23:16:06.230
4,2024-10-20 03:00:00+00:00,1005,0.061675,0.685299,187,2024-11-03 23:16:06.230
...,...,...,...,...,...,...
1802,2024-11-03 21:00:00+00:00,1001,0.225668,0.375757,838,2024-11-03 23:16:06.230
1803,2024-11-03 22:00:00+00:00,1001,0.232792,0.763044,477,2024-11-03 23:16:06.230
1804,2021-04-12 07:00:00+00:00,1001,0.640050,0.359791,438,2024-11-03 23:16:06.230
1805,2024-10-27 11:00:00+00:00,1003,0.139332,0.491269,255,2024-11-03 23:16:06.230
1806,2024-10-27 11:00:00+00:00,1003,0.139332,0.491269,255,2024-11-03 23:16:06.230